version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Javier_1052
      MYSQL_DB: bd_politecnico
    volumes:
      - .:/var/www
    networks:
      - red-network
  web:
        image: nginx:1.19.4
        container_name: test-nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - red-network

  mysql:
    image: mysql:5.7
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Javier_1052
      MYSQL_ROOT_PASSWORD: Javier_1052
      MYSQL_DATABASE: bd_politecnico
    networks:
      - red-network

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - red-network

networks:
    red-network:
        driver: bridge
